/*
 * Parameters.h
 *
 *  Created on: Jun 19, 2017
 *      Author: pauvsi
 */

#ifndef M7_SENSOR_FUSION_INCLUDE_M7_SENSOR_FUSION_PARAMETERS_H_
#define M7_SENSOR_FUSION_INCLUDE_M7_SENSOR_FUSION_PARAMETERS_H_

#define MAXIMUM_OLD_STATES 600

#define BASE_FRAME "base_link"
#define IMU_FRAME "imu_frame"

#define INITIAL_POS_SIGMA 10000
#define INITIAL_VEL_SIGMA 10
#define INITIAL_ACCEL_SIGMA 10
#define INITIAL_QUAT_SIGMA 10
#define INITIAL_OMEGA_SIGMA 10

#define POS_PROCESS_SIGMA 0.1
#define VEL_PROCESS_SIGMA 0.05
#define ACCEL_PROCESS_SIGMA 0.01
#define QUAT_PROCESS_SIGMA 0.1
#define OMEGA_PROCESS_SIGMA 0.01


#define G 9.815



#endif /* M7_SENSOR_FUSION_INCLUDE_M7_SENSOR_FUSION_PARAMETERS_H_ */
